[versions]
agp = "8.11.1"
kotlin = "2.2.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
navigation = "2.9.2"
glide = "5.0.5"
room = "2.8.2"
activity = "1.10.1"
constraintlayout = "2.2.1"
okhttp = "5.2.1"
coroutines = "1.10.2"

[libraries]
# AndroidX
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
# Coroutines
coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "coroutines"}
# Glide
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide"}
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide"}
# Navigation
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation"}
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation"}
# Material
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
# Room
androidx-room = { group = "androidx.room", name = "room-ktx", version.ref = "room"}
androidx-room-compiler = {group = "androidx.room", name = "room-compiler", version.ref = "room"}
#okHttp
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp"}
# Unit Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
navigation-safeArgs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
# KAPT Plugin
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }

[bundles]

androidx = [
    "androidx-core-ktx",
    "androidx-appcompat",
    "androidx-activity",
    "androidx-constraintlayout",
    "androidx-navigation-fragment",
    "androidx-navigation-ui"
]

compiler = [
    "androidx-room-compiler",
    "glide-compiler"
]

test = [
    "androidx-junit",
    "androidx-espresso-core"
]

